In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy import stats
#特征
from sklearn.preprocessing import OneHotEncoder
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [2]:
df1 = pd.read_excel('./F6-C2018-2020.xlsx',)

In [3]:
X = df1.iloc[:,3:]
y = df1['Label']

In [4]:
X

gender   age  resident  resident type  education  marital  occupation  \
0           0  70.0       1.0              1          1        1         1.0   
1           0  70.0       1.0              1          1        1         1.0   
2           1  90.0       1.0              1          1        0         1.0   
3           0  66.0       1.0              1          1        1         1.0   
4           1  79.0       1.0              1          1        1         1.0   
...       ...   ...       ...            ...        ...      ...         ...   
13246       0  63.0       0.0              1          2        1         0.5   
13247       1  60.0       0.0              1          1        1         1.0   
13248       0  61.0       0.0              1          1        1         1.0   
13249       1  70.0       0.0              1          1        1         1.0   
13250       0  69.0       0.0              1          1        1         1.0   

       nation  religion  community  ...  Creatinine  Blood Urea Nitrogen  \
0           1         0          0  ...    0.825226            14.355740   
1           1         0          0  ...    0.604073             8.683472   
2           1         0          0  ...    0.644514            10.364144   
3           1         0          0  ...    0.696833            12.675068   
4           1         0          1  ...    0.915724            12.324928   
...       ...       ...        ...  ...         ...                  ...   
13246       1         0          0  ...    0.598134            11.624648   
13247       1         0          0  ...    0.799774            14.635852   
13248       1         0          0  ...    0.705317            13.445376   
13249       1         0          0  ...    0.887444            16.246496   
13250       1         0          0  ...    0.685521            12.885152   

       High Density Lipoprotein Cholesterol  \
0                                 57.915059   
1                                 43.629345   
2                                 61.003862   
3                                 41.023167   
4                                 38.899615   
...                                     ...   
13246                             50.965251   
13247                             51.737452   
13248                             64.768343   
13249                             63.996141   
13250                             57.722010   

       Low Density Lipoprotein Cholesterol  Total Cholesterol     Glucose  \
0                                87.451738         161.872590   90.090090   
1                                91.891890         153.281860  120.720720   
2                               108.880310         200.579150   87.837838   
3                                90.444016         188.899618   99.099097   
4                                61.583012         122.007726   88.288290   
...                                    ...                ...         ...   
13246                           109.652509         186.196912  134.684686   
13247                            81.370658         156.660233   92.792794   
13248                            93.050194         181.081087   94.594594   
13249                           113.223939         202.895758  107.657657   
13250                            84.266409         173.745180  109.009007   

       Uric Acid  Cystatin C  C-Reactive Protein  Glycated Hemoglobin  
0          4.875      0.7850               0.675                5.750  
1          5.800      0.7200               1.400                5.900  
2          4.725      0.8150               3.425                5.650  
3          5.425      0.8125               5.425                6.200  
4          5.400      0.9150               1.300                5.425  
...          ...         ...                 ...                  ...  
13246      4.650      0.7300               2.175                5.875  
13247      5.800      0.8850               6.675                5.5

In [5]:
from sklearn.preprocessing import StandardScaler
data = X
scaler = StandardScaler() #实例化
scaler.fit(data) #fit，本质是生成均值和方差
scaler.mean_ #查看均值的属性mean_
scaler.var_ #查看方差的属性var_
x_std = scaler.transform(data) #通过接口导出结果
x_std.mean() #导出的结果是一个数组，用mean()查看均值
x_std.std() #用std()查看方差
scaler.fit_transform(data) #使用fit_transform(data)一步达成结果
scaler.inverse_transform(x_std) #使用inverse_transform逆转标准化

X = scaler.fit_transform(data)

In [6]:
y

0        0
1        0
2        0
3        0
4        1
        ..
13246    0
13247    0
13248    0
13249    0
13250    0
Name: Label, Length: 13251, dtype: int64

In [14]:
pca_f = PCA(n_components=0.98,svd_solver="full")
pca_f = pca_f.fit(X)
X_f = pca_f.transform(X)
pca_f.explained_variance_ratio_

array([0.05536419, 0.03472665, 0.02918896, 0.02311477, 0.02175787,
       0.01807708, 0.01720283, 0.01535532, 0.01468472, 0.01409065,
       0.01376354, 0.01302599, 0.01243043, 0.01219374, 0.01204351,
       0.0114761 , 0.01121336, 0.01089425, 0.01066726, 0.0105356 ,
       0.01033395, 0.01009586, 0.01005729, 0.00999101, 0.00982058,
       0.00970179, 0.00968224, 0.00933805, 0.00917421, 0.00906294,
       0.00901302, 0.00889539, 0.00884792, 0.00875395, 0.00867369,
       0.00860052, 0.00850989, 0.0083567 , 0.00828054, 0.00823996,
       0.00822219, 0.00816224, 0.00811055, 0.0080707 , 0.00795436,
       0.00789146, 0.00780373, 0.00775601, 0.00771262, 0.00762454,
       0.00758311, 0.00753229, 0.00752044, 0.00748861, 0.00746267,
       0.00737655, 0.00734669, 0.00729936, 0.00721205, 0.00720043,
       0.00711807, 0.00707265, 0.00701056, 0.00696861, 0.00690759,
       0.00686016, 0.0067623 , 0.00673475, 0.00668307, 0.00662382,
       0.00657988, 0.0065279 , 0.00645658, 0.00641306, 0.00635

In [15]:
#SKB
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif ## 导入 f_classif 检验
from sklearn.feature_selection import SelectKBest,chi2
skb = SelectKBest(f_classif, k=111)
X_new=skb.fit_transform(X, y)
pd.DataFrame(X_new).head(10)

0         1         2         3         4         5         6    \
0 -0.958958 -0.186311  1.814101  0.109987  0.245765  0.455149  0.629657   
1 -0.958958 -0.186311  1.814101  0.109987  0.245765  0.455149  0.629657   
2  1.042799  2.273824  1.814101  0.109987  0.245765 -2.197084  0.629657   
3 -0.958958 -0.678338  1.814101  0.109987  0.245765  0.455149  0.629657   
4  1.042799  0.920750  1.814101  0.109987  0.245765  0.455149  0.629657   
5  1.042799  2.027811  1.814101  0.109987  0.245765  0.455149  0.629657   
6 -0.958958  1.535784  1.814101  0.109987  1.898040  0.455149  0.629657   
7 -0.958958  1.781797  1.814101  0.109987  1.898040  0.455149  0.629657   
8  1.042799  1.781797  1.814101  0.109987  1.898040  0.455149  0.629657   
9 -0.958958  0.305716  1.814101  0.109987  0.245765 -2.197084  0.629657   

        7         8         9    ...       101       102       103       104  \
0  0.272986 -0.342744 -0.337080  ... -1.146458 -0.046784 -0.402389  0.685069   
1  0.272986 -0.342744 -0.337080  ... -0.721500 -1.325638 -2.305178 -1.279549   
2  0.272986 -0.342744 -0.337080  ... -0.370618 -1.091781 -1.741389  1.109851   
3  0.272986 -0.342744 -0.337080  ...  1.843840 -0.789239 -0.966178 -1.637959   
4  0.272986 -0.342744  2.966654  ... -0.670817  0.476533 -1.083635 -1.929996   
5  0.272986 -0.342744 -0.337080  ... -0.479782  0.335892 -1.318547  0.512501   
6  0.272986 -0.342744 -0.337080  ... -0.265353 -1.371429 -1.201091 -0.270691   
7  0.272986 -0.342744 -0.337080  ...  1.165467  1.963079  0.795663 -1.040609   
8  0.272986 -0.342744  2.966654  ...  0.292160  1.284403  1.735312 -1.757429   
9  0.272986  2.917630 -0.337080  ... -0.643527  0.679318 -1.576950  1.773573   

        105       106       107       108       109       110  
0 -0.932548 -1.068683 -0.576268 -0.273283 -0.588905 -0.343202  
1 -0.681073 -1.450001  1.167288  0.759080 -1.063653 -0.057789  
2  0.281091  0.649393 -0.704471 -0.440694 -0.369790 -0.533477  
3 -0.763075  0.130971 -0.063458  0.340554 -0.388050  0.513037  
4 -2.397661 -2.838172 -0.678830  0.312652  0.360591 -0.961596  
5  0.193622  0.152394 -0.576268 -0.245382 -0.789760 -0.771321  
6  0.302959  0.263790 -0.781392 -0.747612 -0.315012 -0.581046  
7 -0.374930  0.070989  0.321150  1.372917  0.725782  0.513037  
8 -0.265593 -0.233209  0.449353  3.437643  3.172560  0.322761  
9 -0.178124  0.293781 -0.550628  0.173144 -0.661943 -0.914028  

[10 rows x 111 columns]

In [16]:
skb.scores_

array([1.02785024e+02, 1.35173445e+02, 1.51605193e+01, 1.43390789e+00,
       8.84380928e+01, 6.40394479e+01, 2.65333687e+01, 6.79633982e+00,
       1.07895117e+01, 1.03475279e+01, 8.81561796e+01, 1.53055993e-01,
       1.54335504e+02, 7.83435033e+01, 6.82416480e+00, 2.09876853e+01,
       6.97714361e+00, 2.43919236e+00, 3.51321194e+01, 9.43905820e+00,
       2.41512853e+01, 6.75201052e+01, 1.46895659e+01, 3.23755716e+01,
       2.56289490e+01, 4.04206965e+01, 3.39543424e+01, 2.03197711e+01,
       2.01551904e+02, 1.56708611e+01, 3.83981154e+01, 3.70953161e+01,
       3.88147381e+01, 4.05002926e+01, 5.35083055e+00, 2.64757123e+02,
       3.60666988e+02, 2.40946642e+02, 1.11890241e+00, 5.38292289e+00,
       1.19599459e+01, 1.60762403e+01, 2.42579260e+01, 1.02466879e+02,
       1.07740757e+02, 5.39103150e+00, 4.81983479e+01, 6.07213280e+00,
       2.30264579e+01, 6.97811386e+01, 1.55595889e+01, 3.48040864e+01,
       2.10884068e+01, 5.31038294e+01, 2.39103922e+01, 3.17868993e+01,
      

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy import stats

In [5]:
df1 = pd.read_csv('./data/latest/HTN-2，Obesity-BMI/13-18-mort.csv',encoding='UTF-8')
df2 = pd.read_csv('./data/latest/HTN-2，Obesity-BMI/2013-2018-F6.csv',encoding='UTF-8')

In [6]:
df3 = pd.merge(df1,df2, on='SEQN', how='left',)

In [7]:
df3

SEQN  eligstat  mortstat  ucod_leading  diabetes  hyperten  \
0       73557         1       0.0           NaN       NaN       NaN   
1       73558         1       1.0           7.0       1.0       0.0   
2       73559         1       0.0           NaN       NaN       NaN   
3       73560         2       NaN           NaN       NaN       NaN   
4       73561         1       1.0          10.0       0.0       0.0   
...       ...       ...       ...           ...       ...       ...   
38055  102956         1       0.0           NaN       NaN       NaN   
38056  102956         1       0.0           NaN       NaN       NaN   
38057  102956         1       0.0           NaN       NaN       NaN   
38058  102956         1       0.0           NaN       NaN       NaN   
38059  102956         1       0.0           NaN       NaN       NaN   

       permth_int  permth_exm RXDRSC1 RXDRSC2  ... URXUSN URXUTL URXUTU  \
0            78.0        78.0     NaN     NaN  ...    NaN    NaN    NaN   
1            58.0        58.0     NaN     NaN  ...    NaN    NaN    NaN   
2            83.0        82.0     NaN     NaN  ...    NaN    NaN    NaN   
3             NaN         NaN                  ...   5.26  0.062  0.238   
4            10.0         9.0     NaN     NaN  ...    NaN    NaN    NaN   
...           ...         ...     ...     ...  ...    ...    ...    ...   
38055        27.0        26.0  T78.40     NaN  ...   0.17  0.076  0.026   
38056        27.0        26.0   F41.9   M79.2  ...   0.17  0.076  0.026   
38057        27.0        26.0   J30.2     NaN  ...   0.17  0.076  0.026   
38058        27.0        26.0   M79.2     NaN  ...   0.17  0.076  0.026   
38059        27.0        26.0   M79.2     NaN  ...   0.17  0.076  0.026   

      LBXBPB  LBXBCD  LBXTHG  LBXBSE  LBXBMN   year  空值计数  
0        NaN     NaN     NaN     NaN     NaN    NaN   NaN  
1        NaN     NaN     NaN     NaN     NaN    NaN   NaN  
2        NaN     NaN     NaN     NaN     NaN    NaN   NaN  
3       0.37    0.07    0.88  169.82   13.07  13-14   1.0  
4        NaN     NaN     NaN     NaN     NaN    NaN   NaN  
...      ...     ...     ...     ...     ...    ...   ...  
38055   0.90    3.96    0.83  233.65    6.14  17-20   0.0  
38056   0.90    3.96    0.83  233.65    6.14  17-20   0.0  
38057   0.90    3.96    0.83  233.65    6.14  17-20   0.0  
38058   0.90    3.96    0.83  233.65    6.14  17-20   0.0  
38059   0.90    3.96    0.83  233.65    6.14  17-20   0.0  

[38060 rows x 38 columns]

In [14]:
#df3.to_csv('./data/latest/HTN-2/2013-2018-F6-mort.csv',encoding='utf_8_sig',index=False)

In [5]:
df1 = pd.read_excel('./data/latest/HTN-2，Obesity-BMI/2013-2018-F8-mort-LABEL.xlsx',)

In [6]:
df1

LABEL  RIAGENDR  RIDAGEYR  RIDRETH3  DMDEDUC2  INDFMPIR  BMXBMI  URXUBA  \
0         0         2        60         4       2.0      5.00    39.1    0.38   
1         0         2        60         4       2.0      5.00    39.1    0.38   
2         0         2        60         4       2.0      5.00    39.1    0.38   
3         0         2        60         4       2.0      5.00    39.1    0.38   
4         0         2        60         4       2.0      5.00    39.1    0.38   
...     ...       ...       ...       ...       ...       ...     ...     ...   
2342      0         2        61         3       3.0      3.86    25.4    1.82   
2343      0         1        67         3       4.0      0.99    48.8    1.77   
2344      0         2        51         6       5.0      5.00    26.4    2.45   
2345      0         2        50         6       5.0       NaN    30.2    1.13   
2346      0         1        80         4       4.0      5.00    28.1    0.39   

      URXUCD  URXUCO  ...  URXUSB  URXUSN  URXUTL  URXUTU  LBXBPB  LBXBCD  \
0      0.136   0.188  ...   0.049    0.80   0.065   0.047    2.23    0.38   
1      0.136   0.188  ...   0.049    0.80   0.065   0.047    2.23    0.38   
2      0.136   0.188  ...   0.049    0.80   0.065   0.047    2.23    0.38   
3      0.136   0.188  ...   0.049    0.80   0.065   0.047    2.23    0.38   
4      0.136   0.188  ...   0.049    0.80   0.065   0.047    2.23    0.38   
...      ...     ...  ...     ...     ...     ...     ...     ...     ...   
2342   0.156   0.627  ...   0.045    0.91   0.331   0.056    0.77    0.20   
2343   1.231   0.339  ...   0.056   12.50   0.188   0.122    0.94    0.65   
2344   0.513   0.315  ...   0.079    0.69   0.200   0.026    1.03    1.34   
2345   0.414   0.359  ...   0.016    0.13   0.101   0.028    0.79    0.90   
2346   0.097   0.120  ...   0.016    0.11   0.035   0.048    3.26    0.24   

      LBXTHG  LBXBSE  LBXBMN   year  
0       2.74  230.23    7.53  13-14  
1       2.74  230.23    7.53  13-14  
2       2.74  230.23    7.53  13-14  
3       2.74  230.23    7.53  13-14  
4       2.74  230.23    7.53  13-14  
...      ...     ...     ...    ...  
2342    1.25  219.39   11.68  17-20  
2343    1.15  193.85    6.64  17-20  
2344    4.85  172.26   11.26  17-20  
2345    0.60  206.38   14.16  17-20  
2346    0.43  174.87    7.62  17-20  

[2347 rows x 24 columns]

In [49]:
df1[df1.LABEL==1].describe()

LABEL    RIAGENDR    RIDAGEYR    RIDRETH3    DMDEDUC2    INDFMPIR  \
count  344.0  344.000000  344.000000  344.000000  344.000000  341.000000   
mean     1.0    1.386628   71.636628    3.031977    3.078488    2.004663   
std      0.0    0.487687   10.023526    1.173875    1.360502    1.407269   
min      1.0    1.000000   26.000000    1.000000    1.000000    0.010000   
25%      1.0    1.000000   65.000000    3.000000    2.000000    1.090000   
50%      1.0    1.000000   76.000000    3.000000    3.000000    1.490000   
75%      1.0    2.000000   80.000000    3.000000    4.000000    2.270000   
max      1.0    2.000000   80.000000    7.000000    9.000000    5.000000   

           BMXBMI      URXUBA      URXUCD      URXUCO  ...      URXUPB  \
count  308.000000  344.000000  344.000000  344.000000  ...  344.000000   
mean    30.747078    0.939244    0.487625    1.164233  ...    0.643314   
std      6.951514    0.932552    0.417119    3.228521  ...    0.516820   
min     16.900000    0.060000    0.025000    0.035000  ...    0.050000   
25%     24.200000    0.290000    0.228000    0.283000  ...    0.280000   
50%     30.800000    0.730000    0.325000    0.513000  ...    0.490000   
75%     35.525000    1.270000    0.731000    0.988750  ...    0.880000   
max     50.600000    7.280000    3.580000   33.719000  ...    3.410000   

           URXUSB      URXUSN      URXUTL      URXUTU      LBXBPB      LBXBCD  \
count  344.000000  344.000000  344.000000  344.000000  344.000000  344.000000   
mean     0.086416    3.307395    0.128840    0.115674    1.746308    0.533285   
std      0.108899   10.115919    0.073602    0.153582    1.011379    0.399600   
min      0.016000    0.064000    0.013000    0.013000    0.330000    0.070000   
25%      0.039000    0.510000    0.076250    0.035750    1.040000    0.250000   
50%      0.061000    0.890000    0.117000    0.079000    1.555000    0.405000   
75%      0.098000    2.330000    0.174250    0.144000    2.307500    0.720000   
max      0.733000   90.970000    0.514000    1.851000    5.750000    2.480000   

           LBXTHG      LBXBSE      LBXBMN  
count  344.000000  344.000000  344.000000  
mean     0.946424  188.244971    8.819302  
std      1.594652   28.668824    2.673499  
min      0.200000  127.330000    1.750000  
25%      0.317500  175.000000    6.610000  
50%      0.520000  189.470000    8.480000  
75%      0.810000  201.750000   10.370000  
max     12.630000  395.060000   20.210000  

[8 rows x 23 columns]

In [7]:
df1.describe()

LABEL     RIAGENDR     RIDAGEYR     RIDRETH3     DMDEDUC2  \
count  2347.000000  2347.000000  2347.000000  2347.000000  2346.000000   
mean      0.146570     1.502769    64.153387     3.379207     3.333333   
std       0.353752     0.500099    12.039236     1.409157     1.286527   
min       0.000000     1.000000    18.000000     1.000000     1.000000   
25%       0.000000     1.000000    57.000000     3.000000     3.000000   
50%       0.000000     2.000000    65.000000     3.000000     3.000000   
75%       0.000000     2.000000    74.000000     4.000000     4.000000   
max       1.000000     2.000000    80.000000     7.000000     9.000000   

          INDFMPIR       BMXBMI       URXUBA       URXUCD       URXUCO  ...  \
count  2141.000000  2293.000000  2347.000000  2347.000000  2347.000000  ...   
mean      2.408660    31.494549     1.301438     0.422803     0.684003  ...   
std       1.564075     7.122596     2.019509     0.434136     1.999225  ...   
min       0.000000    16.900000     0.042000     0.025000     0.027000  ...   
25%       1.090000    26.500000     0.370000     0.146000     0.235000  ...   
50%       1.920000    30.500000     0.760000     0.284000     0.369000  ...   
75%       3.730000    35.400000     1.520000     0.544000     0.578000  ...   
max       5.000000    71.500000    30.600000     7.581000    33.719000  ...   

            URXUPB       URXUSB       URXUSN       URXUTL       URXUTU  \
count  2347.000000  2347.000000  2347.000000  2347.000000  2347.000000   
mean      0.517921     0.069182     1.785563     0.166031     0.102360   
std       0.609543     0.101692     5.586958     0.120238     0.226723   
min       0.020000     0.016000     0.064000     0.013000     0.013000   
25%       0.210000     0.027000     0.300000     0.081000     0.029000   
50%       0.360000     0.046000     0.630000     0.138000     0.058000   
75%       0.640000     0.078000     1.480000     0.214000     0.107500   
max      18.530000     2.761000    92.180000     1.210000     4.616000   

            LBXBPB       LBXBCD       LBXTHG       LBXBSE       LBXBMN  
count  2347.000000  2347.000000  2347.000000  2347.000000  2347.000000  
mean      1.533622     0.534082     1.495313   194.431142     9.328786  
std       1.265095     0.577450     2.574389    27.301688     3.405694  
min       0.050000     0.070000     0.200000   104.730000     1.570000  
25%       0.820000     0.210000     0.420000   178.010000     7.040000  
50%       1.220000     0.360000     0.760000   192.060000     8.840000  
75%       1.875000     0.630000     1.580000   208.055000    11.140000  
max      24.600000     7.500000    63.640000   443.180000    52.000000  

[8 rows x 23 columns]

In [36]:
crosstable1 = pd.crosstab(df1.RIDRETH3, df1.LABEL, margins=True)
crosstable1

LABEL        0    1   All
RIDRETH3                 
1          216   49   265
2          181    9   190
3          712  211   923
4          627   57   684
6          203   11   214
7           64    7    71
All       2003  344  2347

In [37]:
stats.chi2_contingency(crosstable1)

(106.38367664155614,
 3.0981276418718986e-17,
 12,
 array([[ 226.15892629,   38.84107371,  265.        ],
        [ 162.151683  ,   27.848317  ,  190.        ],
        [ 787.71580741,  135.28419259,  923.        ],
        [ 583.7460588 ,  100.2539412 ,  684.        ],
        [ 182.63400085,   31.36599915,  214.        ],
        [  60.59352365,   10.40647635,   71.        ],
        [2003.        ,  344.        , 2347.        ]]))

In [38]:
crosstable2 = np.around((crosstable1.iloc[0:6]/crosstable1.iloc[-1])*100,decimals=2)
crosstable2

LABEL         0      1    All
RIDRETH3                     
1         10.78  14.24  11.29
2          9.04   2.62   8.10
3         35.55  61.34  39.33
4         31.30  16.57  29.14
6         10.13   3.20   9.12
7          3.20   2.03   3.03

In [39]:
crosstable1.iloc[0:6].astype(str)+'('+crosstable2.astype(str)+')'

LABEL              0           1         All
RIDRETH3                                    
1         216(10.78)   49(14.24)  265(11.29)
2          181(9.04)     9(2.62)    190(8.1)
3         712(35.55)  211(61.34)  923(39.33)
4          627(31.3)   57(16.57)  684(29.14)
6         203(10.13)     11(3.2)   214(9.12)
7            64(3.2)     7(2.03)    71(3.03)

In [44]:
#中位数IQR
def DM(x):
    result = np.around(np.median(x),decimals=2).astype(str)+'('+ np.around(np.percentile(x, 25),decimals=2).astype(str)+', '+np.around(np.percentile(x, 75),decimals=2).astype(str)+')'
    return result
    
df2=pd.pivot_table(data=df1
                   ,index=[u'LABEL'],values=[u'BMXBMI']
                   ,aggfunc=DM,
              )
df2

BMXBMI
LABEL               
0      nan(nan, nan)
1      nan(nan, nan)

In [50]:
#均值标准差
def DM(x):
    result = np.around(np.mean(x),decimals=2).astype(str)+'('+np.around(np.std(x),decimals=2).astype(str)+')'
    return result

df2=pd.pivot_table(data=df1
                   ,index=[u'year'],values=[u'URXUBA',u'URXUCD',u'URXUCO',u'URXUCS',u'URXUMO',u'URXUMN',u'URXUPB',u'URXUSB',u'URXUSN',u'URXUTL',u'URXUTU',u'LBXBPB',u'LBXBCD',u'LBXTHG',u'LBXBSE',u'LBXBMN']
                   ,aggfunc=DM,
              )
df2.T

year            13-14         15-16          17-20
LBXBCD     0.52(0.54)    0.54(0.52)     0.54(0.65)
LBXBMN     9.14(3.05)     9.6(3.34)     9.26(3.75)
LBXBPB     1.56(1.37)    1.54(1.31)     1.51(1.11)
LBXBSE  196.55(28.18)   193.6(25.5)  193.15(27.91)
LBXTHG      1.5(2.45)    1.49(2.07)      1.5(3.07)
URXUBA     1.35(2.62)     1.31(1.7)     1.24(1.57)
URXUCD     0.43(0.45)    0.42(0.37)     0.42(0.48)
URXUCO     0.78(2.71)    0.65(1.75)     0.63(1.27)
URXUCS     4.72(3.17)    5.13(3.89)     4.91(3.16)
URXUMN     0.18(0.72)    0.14(0.22)     0.16(0.22)
URXUMO   47.97(41.53)  52.98(51.02)   45.11(37.48)
URXUPB     0.51(0.47)    0.55(0.83)      0.5(0.47)
URXUSB      0.07(0.1)    0.07(0.06)     0.07(0.12)
URXUSN     2.29(8.18)    1.32(2.15)     1.73(4.57)
URXUTL     0.16(0.13)    0.17(0.11)     0.17(0.12)
URXUTU     0.11(0.31)     0.1(0.16)     0.09(0.18)

In [51]:
#df2.T.to_csv('C:/Users/Administrator/Desktop/table2.csv',encoding='utf_8_sig',index=True)

In [69]:
crosstable1 = pd.crosstab(df1.LBXBMN, df1.year, margins=True)
stats.chi2_contingency(crosstable1)

(2831.6252767075525,
 1.0661643055360742e-07,
 2451,
 array([[1.00085215e+00, 9.62505326e-01, 1.03664252e+00, 3.00000000e+00],
        [3.33617384e-01, 3.20835109e-01, 3.45547507e-01, 1.00000000e+00],
        [3.33617384e-01, 3.20835109e-01, 3.45547507e-01, 1.00000000e+00],
        ...,
        [3.33617384e-01, 3.20835109e-01, 3.45547507e-01, 1.00000000e+00],
        [3.33617384e-01, 3.20835109e-01, 3.45547507e-01, 1.00000000e+00],
        [7.83000000e+02, 7.53000000e+02, 8.11000000e+02, 2.34700000e+03]]))

In [70]:
#特征
from sklearn.preprocessing import OneHotEncoder
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [72]:
d1 = df1['RIAGENDR'].values.reshape(-1, 1)
d2 = df1['RIDRETH3'].values.reshape(-1, 1)
d3 = df1['DMDEDUC2'].values.reshape(-1, 1)
df1['RIAGENDR'] = OneHotEncoder(categories='auto').fit_transform(d1).toarray()
df1['RIDRETH3'] = OneHotEncoder(categories='auto').fit_transform(d2).toarray()
df1['DMDEDUC2'] = OneHotEncoder(categories='auto').fit_transform(d3).toarray()

In [90]:
df1=df1.dropna()

In [91]:
X = df1.iloc[:,1:23]
y = df1['LABEL']

In [92]:
X

RIAGENDR  RIDAGEYR  RIDRETH3  DMDEDUC2  INDFMPIR  BMXBMI  URXUBA  \
0          0.0        60       0.0       0.0      5.00    39.1    0.38   
1          0.0        60       0.0       0.0      5.00    39.1    0.38   
2          0.0        60       0.0       0.0      5.00    39.1    0.38   
3          0.0        60       0.0       0.0      5.00    39.1    0.38   
4          0.0        60       0.0       0.0      5.00    39.1    0.38   
...        ...       ...       ...       ...       ...     ...     ...   
2341       0.0        67       0.0       0.0      0.85    36.4    0.28   
2342       0.0        61       0.0       0.0      3.86    25.4    1.82   
2343       1.0        67       0.0       0.0      0.99    48.8    1.77   
2344       0.0        51       0.0       0.0      5.00    26.4    2.45   
2346       1.0        80       0.0       0.0      5.00    28.1    0.39   

      URXUCD  URXUCO  URXUCS  ...  URXUPB  URXUSB  URXUSN  URXUTL  URXUTU  \
0      0.136   0.188   3.080  ...    0.35   0.049    0.80   0.065   0.047   
1      0.136   0.188   3.080  ...    0.35   0.049    0.80   0.065   0.047   
2      0.136   0.188   3.080  ...    0.35   0.049    0.80   0.065   0.047   
3      0.136   0.188   3.080  ...    0.35   0.049    0.80   0.065   0.047   
4      0.136   0.188   3.080  ...    0.35   0.049    0.80   0.065   0.047   
...      ...     ...     ...  ...     ...     ...     ...     ...     ...   
2341   1.020   0.831  11.614  ...    2.96   0.094    0.99   0.177   0.966   
2342   0.156   0.627   4.325  ...    0.19   0.045    0.91   0.331   0.056   
2343   1.231   0.339   4.882  ...    0.56   0.056   12.50   0.188   0.122   
2344   0.513   0.315   6.590  ...    0.25   0.079    0.69   0.200   0.026   
2346   0.097   0.120   1.723  ...    0.44   0.016    0.11   0.035   0.048   

      LBXBPB  LBXBCD  LBXTHG  LBXBSE  LBXBMN  
0       2.23    0.38    2.74  230.23    7.53  
1       2.23    0.38    2.74  230.23    7.53  
2       2.23    0.38    2.74  230.23    7.53  
3       2.23    0.38    2.74  230.23    7.53  
4       2.23    0.38    2.74  230.23    7.53  
...      ...     ...     ...     ...     ...  
2341    2.99    0.35    4.49  214.75    8.53  
2342    0.77    0.20    1.25  219.39   11.68  
2343    0.94    0.65    1.15  193.85    6.64  
2344    1.03    1.34    4.85  172.26   11.26  
2346    3.26    0.24    0.43  174.87    7.62  

[2088 rows x 22 columns]

In [93]:
from sklearn.preprocessing import StandardScaler
data = X
scaler = StandardScaler() #实例化
scaler.fit(data) #fit，本质是生成均值和方差
scaler.mean_ #查看均值的属性mean_
scaler.var_ #查看方差的属性var_
x_std = scaler.transform(data) #通过接口导出结果
x_std.mean() #导出的结果是一个数组，用mean()查看均值
x_std.std() #用std()查看方差
scaler.fit_transform(data) #使用fit_transform(data)一步达成结果
scaler.inverse_transform(x_std) #使用inverse_transform逆转标准化

X = scaler.fit_transform(data)

In [94]:
y

0       0
1       0
2       0
3       0
4       0
       ..
2341    0
2342    0
2343    0
2344    0
2346    0
Name: LABEL, Length: 2088, dtype: int64

In [118]:
#PCA
pca = PCA(n_components=19)
pca = pca.fit(X) 
X_dr = pca.transform(X) 

In [119]:
#属性explained_variance，查看降维后每个新特征向量上所带的信息量大小（可解释性方差的大小）
pca.explained_variance_

array([2.77211401, 1.97703259, 1.66907954, 1.41901435, 1.37655095,
       1.12007798, 1.11187739, 1.02344103, 0.98714149, 0.97008365,
       0.92662205, 0.88974488, 0.87755093, 0.76437652, 0.71412413,
       0.66515095, 0.62744762, 0.5615223 , 0.52244942])

In [120]:
#属性explained_variance_ratio，查看降维后每个新特征向量所占的信息量占原始数据总信息量的百分比
#又叫做可解释方差贡献率
pca.explained_variance_ratio_

array([0.12594483, 0.08982208, 0.07583092, 0.06446976, 0.06254053,
       0.05088825, 0.05051568, 0.04649777, 0.04484858, 0.04407359,
       0.04209901, 0.04042358, 0.03986957, 0.03472775, 0.03244464,
       0.03021965, 0.02850669, 0.02551152, 0.02373633])

In [121]:
#大部分信息都被有效地集中在了第一个特征上
pca.explained_variance_ratio_.sum()

0.952970731093535

In [117]:
pca_f = PCA(n_components=0.95,svd_solver="full")
pca_f = pca_f.fit(X)
X_f = pca_f.transform(X)
pca_f.explained_variance_ratio_

array([0.12594483, 0.08982208, 0.07583092, 0.06446976, 0.06254053,
       0.05088825, 0.05051568, 0.04649777, 0.04484858, 0.04407359,
       0.04209901, 0.04042358, 0.03986957, 0.03472775, 0.03244464,
       0.03021965, 0.02850669, 0.02551152, 0.02373633])

In [110]:
#SKB
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif ## 导入 f_classif 检验
from sklearn.feature_selection import SelectKBest,chi2
skb = SelectKBest(f_classif, k=18)
X_new=skb.fit_transform(X, y)
pd.DataFrame(X_new).head(10)

0         1         2         3         4         5         6   \
0 -0.990467 -0.348180 -0.350115 -0.367967  1.645012 -0.464010 -0.682922   
1 -0.990467 -0.348180 -0.350115 -0.367967  1.645012 -0.464010 -0.682922   
2 -0.990467 -0.348180 -0.350115 -0.367967  1.645012 -0.464010 -0.682922   
3 -0.990467 -0.348180 -0.350115 -0.367967  1.645012 -0.464010 -0.682922   
4 -0.990467 -0.348180 -0.350115 -0.367967  1.645012 -0.464010 -0.682922   
5  1.009625 -2.094375 -0.350115 -0.367967 -1.143922 -0.243753  0.517893   
6  1.009625 -2.094375 -0.350115 -0.367967 -1.143922 -0.243753  0.517893   
7  1.009625  0.483342 -0.350115 -0.367967  0.889014 -0.407665  0.141555   
8  1.009625  0.483342 -0.350115 -0.367967  0.889014 -0.407665  0.141555   
9  1.009625  0.732798 -0.350115 -0.367967  1.645012 -0.141309 -0.400669   

         7         8         9         10        11        12        13  \
0 -0.236546 -0.598254 -0.255597 -0.177755 -0.176720 -0.824385 -0.302307   
1 -0.236546 -0.598254 -0.255597 -0.177755 -0.176720 -0.824385 -0.302307   
2 -0.236546 -0.598254 -0.255597 -0.177755 -0.176720 -0.824385 -0.302307   
3 -0.236546 -0.598254 -0.255597 -0.177755 -0.176720 -0.824385 -0.302307   
4 -0.236546 -0.598254 -0.255597 -0.177755 -0.176720 -0.824385 -0.302307   
5 -0.198265 -0.333037 -0.174339  0.349655 -0.196591 -1.055268  0.035206   
6 -0.198265 -0.333037 -0.174339  0.349655 -0.196591 -1.055268  0.035206   
7  0.300349  1.262322  0.768253  0.109923 -0.146914  0.363014  3.379655   
8  0.300349  1.262322  0.768253  0.109923 -0.146914  0.363014  3.379655   
9 -0.119310 -0.196820  0.329460  1.116799 -0.266140  1.599888 -0.105936   

         14        15        16        17  
0  0.547064  0.510764  1.282777 -0.544252  
1  0.547064  0.510764  1.282777 -0.544252  
2  0.547064  0.510764  1.282777 -0.544252  
3  0.547064  0.510764  1.282777 -0.544252  
4  0.547064  0.510764  1.282777 -0.544252  
5  0.166315 -0.471744 -0.611549  0.926672  
6  0.166315 -0.471744 -0.611549  0.926672  
7  0.135234  1.850549  0.260598  0.876959  
8  0.135234  1.850549  0.260598  0.876959  
9  0.539294  0.222508  0.869827 -0.553025

In [111]:
pd.DataFrame(X).head(10)

0         1         2         3         4         5         6   \
0 -0.990467 -0.348180 -0.350115 -0.367967  1.645012  1.065238 -0.464010   
1 -0.990467 -0.348180 -0.350115 -0.367967  1.645012  1.065238 -0.464010   
2 -0.990467 -0.348180 -0.350115 -0.367967  1.645012  1.065238 -0.464010   
3 -0.990467 -0.348180 -0.350115 -0.367967  1.645012  1.065238 -0.464010   
4 -0.990467 -0.348180 -0.350115 -0.367967  1.645012  1.065238 -0.464010   
5  1.009625 -2.094375 -0.350115 -0.367967 -1.143922 -1.148531 -0.243753   
6  1.009625 -2.094375 -0.350115 -0.367967 -1.143922 -1.148531 -0.243753   
7  1.009625  0.483342 -0.350115 -0.367967  0.889014 -0.739618 -0.407665   
8  1.009625  0.483342 -0.350115 -0.367967  0.889014 -0.739618 -0.407665   
9  1.009625  0.732798 -0.350115 -0.367967  1.645012 -0.640915 -0.141309   

         7         8         9   ...        12        13        14        15  \
0 -0.682922 -0.236546 -0.530323  ... -0.255597 -0.177755 -0.176720 -0.824385   
1 -0.682922 -0.236546 -0.530323  ... -0.255597 -0.177755 -0.176720 -0.824385   
2 -0.682922 -0.236546 -0.530323  ... -0.255597 -0.177755 -0.176720 -0.824385   
3 -0.682922 -0.236546 -0.530323  ... -0.255597 -0.177755 -0.176720 -0.824385   
4 -0.682922 -0.236546 -0.530323  ... -0.255597 -0.177755 -0.176720 -0.824385   
5  0.517893 -0.198265 -0.906210  ... -0.174339  0.349655 -0.196591 -1.055268   
6  0.517893 -0.198265 -0.906210  ... -0.174339  0.349655 -0.196591 -1.055268   
7  0.141555  0.300349  0.758185  ...  0.768253  0.109923 -0.146914  0.363014   
8  0.141555  0.300349  0.758185  ...  0.768253  0.109923 -0.146914  0.363014   
9 -0.400669 -0.119310  1.057972  ...  0.329460  1.116799 -0.266140  1.599888   

         16        17        18        19        20        21  
0 -0.302307  0.547064 -0.257122  0.510764  1.282777 -0.544252  
1 -0.302307  0.547064 -0.257122  0.510764  1.282777 -0.544252  
2 -0.302307  0.547064 -0.257122  0.510764  1.282777 -0.544252  
3 -0.302307  0.547064 -0.257122  0.510764  1.282777 -0.544252  
4 -0.302307  0.547064 -0.257122  0.510764  1.282777 -0.544252  
5  0.035206  0.166315  1.280049 -0.471744 -0.611549  0.926672  
6  0.035206  0.166315  1.280049 -0.471744 -0.611549  0.926672  
7  3.379655  0.135234 -0.474134  1.850549  0.260598  0.876959  
8  3.379655  0.135234 -0.474134  1.850549  0.260598  0.876959  
9 -0.105936  0.539294 -0.094363  0.222508  0.869827 -0.553025  

[10 rows x 22 columns]

In [112]:
skb.scores_

array([1.12138464e+01, 1.48726610e+02, 7.42281362e+00, 3.71840213e+01,
       2.95722867e+01, 4.23228181e+00, 1.08310462e+01, 8.69604672e+00,
       1.23667056e+01, 1.62051639e-01, 2.12392634e+01, 1.82366912e-03,
       1.50869920e+01, 8.43476748e+00, 2.53210035e+01, 3.00403473e+01,
       5.48998987e+00, 6.95838469e+00, 9.59669178e-03, 1.39899146e+01,
       1.97150267e+01, 7.56583465e+00])